# Starter pipeline
trigger: 
- master
 
pool: 
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'ARM-Deployments'
    subscriptionId: 'a84771c4-d59c-4233-8c65-9e7c8e404eac'
    location: 'Canada Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/naeemhaq/sign-in-canada/master/gluu-az-template/template2/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/naeemhaq/sign-in-canada/master/gluu-az-template/template2/parameters.json'
    overrideParameters: '–devName "$(devopspipeline)'
    deploymentMode: 'Incremental'
    deploymentName: 'pipeline'
    addSpnToEnvironment: true